Repository typicalbot/typicalbot, pull requests merged in 2019-08, with the labels that each got.

#24 Update `donate` command messages
  src/commands/core/donate.js
Labels: status: completed, type: enhancement

#25 Fix typos in music commands
  src/commands/music/current.js
  src/commands/music/pause.js
  src/commands/music/queue.js
  src/commands/music/resume.js
  src/commands/music/skip.js
  src/commands/music/stop.js
  src/commands/music/unqueue.js
  src/commands/music/volume.js
Labels: category: music, status: completed, type: fix

#26 Add contributors
  README.md
Labels: meta, status: completed

#27 Make `eslint` a dev dependency
  package.json
Labels: status/completed, type/fix

#28 Update README
  README.md
Labels: status/completed, type/meta

#29 Improve randomuser command
  src/commands/utility/randomuser.js
Labels: complete, enhancement, utility

#30 Starboard Improvements
  src/commands/moderation/ignore.js
  src/commands/moderation/settings.js
  src/commands/moderation/unignore.js
  src/events/messageReactionAdd.js
  src/structures/Settings.js
Labels: enhancement

#31 Automatic Role for Bots
  src/commands/moderation/settings.js
  src/events/guildMemberAdd.js
  src/structures/Settings.js
Labels: complete, enhancement, feature, moderation

#34 Improve PR template
  .github/PULL_REQUEST_TEMPLATE.MD
  .github/PULL_REQUEST_TEMPLATE.md
Labels: complete, meta

#36 Remove infomation command and make it an alias
  src/commands/core/help.js
  src/commands/core/information.js
Labels: complete, core

#37 Move servers command from core to utility
  src/commands/utility/servers.js
Labels: complete, core, utility

#39 Starboard improvements using partials
  src/events/message.js
  src/events/messageDelete.js
  src/events/messageReactionAdd.js
  src/events/messageReactionRemove.js
  src/events/messageUpdate.js
  src/index.js
Labels: complete, enhancement, feature

#41 Fix $ignore and $unignore commands
  src/commands/moderation/ignore.js
  src/commands/moderation/unignore.js
Labels: complete, fix
