Repository typicalbot/typicalbot, pull requests merged in 2019-10, with the labels that each got.

#82 Remove prime requirement
  CHANGELOG.md
  package.json
  src/commands/moderation/alias.js
  src/commands/moderation/settings.js
  src/commands/music/play.js
Labels: command: moderation, command: music, merge, sem: minor, status: complete

#69 Adopt Conventional Commits
  .github/CONTRIBUTING.md
Labels: sem: none, status: complete, type: chore

#85 Fix message showing modlogs-purge setting
  src/commands/moderation/settings.js
Labels: hacktoberfest, sem: patch, status: complete, type: fix

#84 Remove message upload to hastebin and fix setting checks
  src/events/messageDeleteBulk.js
Labels: hacktoberfest, sem: patch, status: complete, type: fix

#83 Fix autorole-silent check
  src/events/guildMemberAdd.js
Labels: hacktoberfest, sem: patch, status: complete, type: fix
