Repository typicalbot/typicalbot, pull requests merged in 2020-05, with the labels that each got.

#214 fix: `randomuser` role filter not working
  src/commands/utility/randomuser.ts
Labels: sem: patch, status: wip, type: fix

#215 feat: add version field to `help` command
  src/commands/core/help.ts
Labels: sem: minor, status: complete, type: feat

#207 fix: `settings` command gives no response on invalid boolean type
  src/commands/administration/settings.ts
Labels: sem: patch, status: complete, type: fix

#206 fix: `reason` error response
  etc/languages/en-US/moderation/reason.json
Labels: sem: patch, status: complete, type: fix

#224 fix: `twitch` response embed empty value
  src/commands/utility/twitch.ts
Labels: sem: patch, status: complete, type: fix

#223 fix: check ban members permission before fetching
  src/events/guildMemberRemove.ts
Labels: sem: patch, status: complete, type: fix

#225 fix: i18n problem and non-existent page access information, fixes #211 and #212
  etc/languages/en-US/administration/settings.json
  src/commands/administration/settings.ts
Labels: sem: patch, status: complete, type: fix

#182 feat: add `language` command
  etc/languages/en-US/core/language.json
  etc/languages/en-US/misc.json
  src/commands/administration/settings.ts
  src/commands/core/language.ts
  src/lib/extensions/TypicalMessage.ts
  src/lib/types/typicalbot.d.ts
Labels: sem: minor, status: complete, type: feat

#230 fix: remove skin tone from emoji, fixes #229
  etc/languages/de-DE/fun/punch.json
  etc/languages/de-DE/fun/slap.json
  etc/languages/en-US/fun/punch.json
  etc/languages/en-US/fun/slap.json
  etc/languages/fr-FR/fun/punch.json
  etc/languages/fr-FR/fun/slap.json
  etc/languages/ru-RU/fun/punch.json
  etc/languages/ru-RU/fun/slap.json
  etc/languages/sl-SL/fun/punch.json
  etc/languages/sl-SL/fun/slap.json
  etc/languages/sv-SE/fun/punch.json
  etc/languages/sv-SE/fun/slap.json
  etc/languages/tr-TR/fun/punch.json
  etc/languages/tr-TR/fun/slap.json
Labels: sem: patch, status: complete, type: fix, type: i18n

#233 refactor: use custom api for canvas instead of bot process
  .github/workflows/build.yml
  .github/workflows/lint.yml
  .gitignore
  package.json
  src/commands/utility/hex.ts
  src/index.ts
  yarn.lock
Labels: sem: patch, status: complete, type: refactor

#231 feat: account age on join log
  etc/languages/en-US/help/logs.json
  etc/languages/en-US/time.json
  src/events/guildMemberAdd.ts
  src/functions/convertTime.ts
  src/lib/types/typicalbot.d.ts
Labels: sem: minor, status: complete, type: feat

#240 fix: edited cases don't display moderator id
  src/handlers/ModerationLogHandler.ts
Labels: sem: patch, status: complete, type: fix

#245 fix: missing perms check
  etc/languages/en-US/common.json
  src/commands/moderation/ban.ts
  src/commands/moderation/give.ts
  src/commands/moderation/kick.ts
  src/commands/moderation/mute.ts
  src/commands/moderation/purge.ts
  src/commands/moderation/roles.ts
  src/commands/moderation/softban.ts
  src/commands/moderation/take.ts
  src/commands/moderation/unban.ts
  src/commands/moderation/unmute.ts
  src/commands/moderation/voicekick.ts
Labels: sem: minor, status: complete, type: feat
