Repository typicalbot/typicalbot, pull requests merged in 2020-02, with the labels that each got.

#112 Use Managers instead of DataStores
  index.ts
  src/commands/core/stats.ts
  src/commands/moderation/adcheck.ts
  src/commands/moderation/announce.ts
  src/commands/moderation/dehoist.ts
  src/commands/moderation/give.ts
  src/commands/moderation/mute.ts
  src/commands/moderation/purge.ts
  src/commands/moderation/roles.ts
  src/commands/moderation/say.ts
  src/commands/moderation/settings.ts
  src/commands/moderation/take.ts
  src/commands/moderation/unmute.ts
  src/commands/utility/discriminator.ts
  src/commands/utility/randomuser.ts
  src/commands/utility/search.ts
  src/commands/utility/serverinfo.ts
  src/commands/utility/servers.ts
  src/commands/utility/subscribe.ts
  src/commands/utility/unsubscribe.ts
  src/commands/utility/userinfo.ts
  src/events/guildBanAdd.ts
  src/events/guildBanRemove.ts
  src/events/guildInvitePosted.ts
  src/events/guildMemberAdd.ts
  src/events/guildMemberRemove.ts
  src/events/guildMemberUpdate.ts
  src/events/messageDelete.ts
  src/events/messageDeleteBulk.ts
  src/events/messageReactionAdd.ts
  src/events/messageReactionRemove.ts
  src/functions/resolveMember.ts
  src/handlers/ModerationLog.ts
  src/index.ts
  src/permissions/ServerAdministrator.ts
  src/permissions/ServerBlacklisted.ts
  src/permissions/ServerDJ.ts
  src/permissions/ServerModerator.ts
  src/structures/PermissionLevel.ts
  src/tasks/unban.ts
  src/tasks/unmute.ts
Labels: sem: patch, status: complete, type: fix

#114 chore(github): update funding to add github sponsors
  .github/FUNDING.yml
Labels: sem: none, status: complete, type: chore

#115 fix(stats): use managers
  src/commands/core/stats.ts
Labels: sem: patch, status: complete, type: fix

#116 [3.x] fix: permission outputting Object instead of permission title
  README.md
  src/commands/core/credits.ts
  src/commands/core/documentation.ts
  src/commands/core/donate.ts
  src/commands/core/help.ts
  src/commands/core/invite.ts
  src/commands/core/stats.ts
  src/commands/fun/bunny.ts
  src/commands/fun/cat.ts
  src/commands/fun/dog.ts
  src/commands/moderation/adcheck.ts
  src/commands/utility/hex.ts
  src/commands/utility/level.ts
  src/commands/utility/serverinfo.ts
  src/commands/utility/servers.ts
  src/commands/utility/subscribe.ts
  src/commands/utility/twitch.ts
  src/commands/utility/unsubscribe.ts
  src/commands/utility/urban.ts
  src/commands/utility/userinfo.ts
  src/extensions/TypicalMessage.ts
  src/types/typicalbot.d.ts
Labels: sem: patch, status: complete, type: fix

#118 fix: settings cache bug
  src/handlers/Database.ts
  src/handlers/Settings.ts
Labels: bug, bug: fixed, sem: patch, status: complete, type: fix

#120 chore(license): update copyright info
  LICENSE
Labels: status: complete, type: chore

#123 [3.x] Fix Typescript Compile Bug, Automessage bug, Mute response bug
  package-lock.json
  src/commands/moderation/mute.ts
  src/events/guildBanAdd.ts
  src/events/guildBanRemove.ts
  src/events/guildInvitePosted.ts
  src/events/guildMemberAdd.ts
  src/events/guildMemberRemove.ts
  src/events/guildMemberUpdate.ts
  src/events/messageDelete.ts
  src/types/typicalbot.d.ts
  tsconfig.json
Labels: bug: fixed, sem: patch, status: complete, type: fix

#124 [3.x] fix: bots not mentioning users; sending success message on duplicate setting
  src/commands/moderation/say.ts
  src/extensions/TypicalMessage.ts
  src/functions/formatMessage.ts
  src/handlers/Settings.ts
  src/index.ts
Labels: sem: patch, status: complete, type: fix
