Repository typicalbot/typicalbot, pull requests merged in 2020-07, with the labels that each got.

#281 feat: `follow` command to follow TB news channels
  etc/languages/en-US/core/follow.json
  src/commands/core/follow.ts
Labels: sem: minor, type: feat

#288 fix: posting bot stats to DEL api
  src/lib/TypicalClient.ts
Labels: sem: patch, status: complete, type: fix, version: 3.x

#289 fix: `help` response mentioning other users
  src/commands/core/help.ts
  src/lib/extensions/TypicalMessage.ts
Labels: sem: patch, status: complete, type: fix, version: 3.x

#291 feat: remove play command
  etc/languages/en-US/system/play.json
  src/commands/system/play.ts
Labels: sem: minor, status: complete, type: feat, version: 3.x

#296 chore: update codeowners
  .github/CODEOWNERS
Labels: sem: none, status: complete, type: chore, version: 3.x

#293 refactor: serverinfo description
  etc/languages/en-US/utility/serverinfo.json
Labels: sem: patch, status: complete, type: refactor, version: 3.x

#294 refactor: userinfo description
  etc/languages/en-US/utility/userinfo.json
Labels: status: complete

#295 refactor: move cookie, hug, punch, shoot, slap, stab into new category
  etc/languages/en-US/interaction/cookie.json
  etc/languages/en-US/interaction/hug.json
  etc/languages/en-US/interaction/punch.json
  etc/languages/en-US/interaction/shoot.json
  etc/languages/en-US/interaction/slap.json
  etc/languages/en-US/interaction/stab.json
  src/commands/interaction/cookie.ts
  src/commands/interaction/hug.ts
  src/commands/interaction/punch.ts
  src/commands/interaction/shoot.ts
  src/commands/interaction/slap.ts
  src/commands/interaction/stab.ts
Labels: sem: patch, status: complete, type: refactor, version: 3.x

#297 refactor: reduce message lifetime & sweep interval; incease cache size
  src/lib/TypicalClient.ts
Labels: sem: patch, status: complete, type: refactor, version: 3.x

#302 fix: search command mentions
  src/commands/utility/search.ts
Labels: sem: patch, status: complete, type: fix, version: 3.x

#300 refactor: TypicalFunction into utility functions
  src/commands/administration/settings.ts
  src/commands/core/stats.ts
  src/commands/moderation/give.ts
  src/commands/moderation/roles.ts
  src/commands/moderation/take.ts
  src/commands/utility/discriminator.ts
  src/commands/utility/level.ts
  src/commands/utility/nickname.ts
  src/commands/utility/search.ts
  src/commands/utility/userinfo.ts
  src/events/guildBanAdd.ts
  src/events/guildBanRemove.ts
  src/events/guildInvitePosted.ts
  src/events/guildMemberAdd.ts
  src/events/guildMemberRemove.ts
  src/events/guildMemberUpdate.ts
  src/events/message.ts
  src/events/messageDelete.ts
  src/functions/convertTime.ts
  src/functions/fetchAccess.ts
  src/functions/formatMessage.ts
  src/functions/lengthen.ts
  src/functions/pagify.ts
  src/functions/permissionError.ts
  src/functions/resolveMember.ts
  src/handlers/FunctionHandler.ts
  src/lib/TypicalClient.ts
  src/lib/structures/ModerationLog.ts
  src/lib/types/typicalbot.d.ts
  src/lib/utils/util.ts
Labels: status: complete

#301 feat: bulgarian language
  src/commands/administration/settings.ts
Labels: status: complete

#298 feat: meme command
  etc/languages/en-US/fun/meme.json
  src/commands/fun/meme.ts
Labels: sem: minor, status: complete, type: feat, version: 3.x

#310 chore: update codeowners
  .github/CODEOWNERS
Labels: sem: none, status: complete, type: chore

#316 fix: hide system commands
  src/commands/core/help.ts
Labels: sem: patch, status: complete, type: fix

#308 refactor: remove strings for eval command
  etc/languages/en-US/system/eval.json
Labels: sem: patch, status: complete, type: refactor

#314 refactor: core category to general
  etc/languages/en-US/general/commands.json
  etc/languages/en-US/general/documentation.json
  etc/languages/en-US/general/donate.json
  etc/languages/en-US/general/follow.json
  etc/languages/en-US/general/help.json
  etc/languages/en-US/general/invite.json
  etc/languages/en-US/general/language.json
  etc/languages/en-US/general/ping.json
  etc/languages/en-US/general/stats.json
  etc/languages/en-US/general/vote.json
  src/commands/general/commands.ts
  src/commands/general/documentation.ts
  src/commands/general/donate.ts
  src/commands/general/follow.ts
  src/commands/general/help.ts
  src/commands/general/invite.ts
  src/commands/general/language.ts
  src/commands/general/ping.ts
  src/commands/general/stats.ts
  src/commands/general/vote.ts
  src/commands/moderation/roles.ts
  src/events/guildInvitePosted.ts
Labels: sem: patch, status: complete, type: refactor

#318 fix: say mentions
  src/commands/moderation/say.ts
Labels: sem: patch, status: complete, type: fix

#306 feat: profiler command
  etc/languages/en-US/general/stats.json
  package.json
  src/commands/general/stats.ts
  src/commands/system/profiler.ts
  src/lib/TypicalClient.ts
  yarn.lock
Labels: sem: minor, status: complete, type: feat

#323 refactor: help - deconstruct i18n string
  etc/languages/en-US/general/help.json
  src/commands/general/help.ts
Labels: sem: patch, status: complete, type: refactor

#324 refactor: ask method - string i18n deconstruct
  etc/languages/en-US/misc.json
  src/lib/extensions/TypicalMessage.ts
Labels: sem: patch, status: complete, type: refactor

#325 chore: custom release headings (GH releases)
  package.json
  release.js
  yarn.lock
Labels: sem: none, status: complete, type: chore
