Repository typicalbot/typicalbot, pull requests merged in 2020-04, with the labels that each got.

#129 chore: update urls
  package.json
Labels: sem: none, status: complete, type: chore

#130 fix: set presence in client options
  src/events/ready.ts
  src/index.ts
Labels: sem: patch, status: complete, type: fix

#133 fix: autorole-silent check
  src/events/guildMemberAdd.ts
Labels: sem: patch, status: complete, type: fix

#155 fix: `twitch` command error, closes #152
  src/commands/utility/twitch.ts
Labels: sem: patch, status: complete, type: fix

#154 feat: implement `dmcommands` setting
  etc/languages/en-US/administration/settings.json
  src/commands/administration/settings.ts
  src/commands/core/commands.ts
  src/structures/Settings.ts
  src/types/typicalbot.d.ts
Labels: sem: minor, status: complete, type: feat

#157 fix: no response if no embed permission, closes #156
  src/commands/core/commands.ts
Labels: sem: patch, status: complete, type: fix

#158 fix: commands still not responding with no embed permission, wrong check
  src/commands/core/commands.ts
Labels: sem: patch, status: complete, type: fix

#159 chore: update lint-staged config to run lint on committed files only
  package.json
Labels: sem: none, status: complete, type: chore

#160 fix: commands once and for all
  src/commands/core/commands.ts
Labels: sem: patch, status: complete, type: fix

#161 chore(release): 3.2.0
  CHANGELOG.md
  package.json
Labels: sem: minor, status: complete, type: chore, type: release

#166 feat: change default value for `embed` setting
  src/structures/Settings.ts
Labels: sem: minor, status: complete, type: feat

#167 chore: update readme, add security policy
  .all-contributorsrc
  .github/SECURITY.md
  README.md
  package.json
Labels: sem: none, type: chore

#170 chore: add issue template config
  .github/ISSUE_TEMPLATE/config.yml
Labels: sem: none, status: complete, type: chore

#171 chore: remove unused strings
  etc/languages/en-US/administration/settings.json
Labels: sem: none, status: complete, type: chore

#172 chore: remove api types - unused
  src/types/apis.d.ts
Labels: sem: none, status: complete, type: chore

#173 refactor: move index (root) into src dir; rename old index to client
  bin/pm2.ts
  index.ts
  package.json
  src/client.ts
  src/handlers/AnalyticHandler.ts
  src/handlers/CommandHandler.ts
  src/handlers/DatabaseHandler.ts
  src/handlers/EventHandler.ts
  src/handlers/FunctionHandler.ts
  src/handlers/ModerationLogHandler.ts
  src/handlers/PermissionsHandler.ts
  src/handlers/SettingHandler.ts
  src/handlers/TaskHandler.ts
  src/index.ts
  src/structures/Command.ts
  src/structures/Event.ts
  src/structures/Function.ts
  src/structures/ModerationLog.ts
  src/structures/PermissionLevel.ts
  src/structures/Task.ts
  src/types/discord.d.ts
  src/types/typicalbot.d.ts
  tsconfig.json
Labels: sem: patch, status: complete, type: refactor

#176 fix: `settings clear` responding with invalid usage
  src/commands/administration/settings.ts
Labels: sem: patch, status: complete, type: fix

#178 handle potential undefined settings
  src/extensions/TypicalGuild.ts
Labels: sem: patch, status: complete, type: fix

#183 Update purge.ts
  src/commands/moderation/purge.ts
Labels: sem: patch, status: complete, type: fix

#186 delete invite alert
  src/events/guildInvitePosted.ts
Labels: sem: minor, status: complete, type: feat

#189 custom event typings
  src/types/discord.d.ts
Labels: sem: none, status: complete, type: refactor

#188 use current count
  src/events/guildInvitePosted.ts
Labels: sem: patch, status: complete, type: fix

#193 feat: use application owner(s) instead of config option
  etc/config.example.json
  src/commands/system/eval.ts
  src/events/message.ts
  src/events/ready.ts
  src/lib/TypicalClient.ts
  src/lib/utils/constants.ts
  src/permissions/BotOwner.ts
Labels: sem: minor, status: complete, type: feat

#197 fix: `randomuser` command to pick user by role
  src/commands/utility/randomuser.ts
Labels: sem: patch, status: complete, type: fix

#192 feat: honor the verificationLevel of a guild with `autorole` and `autorole-delay`
  etc/languages/en-US/administration/settings.json
  src/commands/administration/settings.ts
  src/events/guildMemberAdd.ts
Labels: sem: minor, status: complete, type: feat
